[licenses]
allow-osi-fsf-free = "both"
copyleft = "deny"
default = "deny"
allow = ["Unicode-DFS-2016", "CC0-1.0", "OpenSSL"]
private = { ignore = true }

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
