[licenses]
allow = [
    "0BSD",
    "Apache-2.0 WITH LLVM-exception",
    "Apache-2.0",
    "BSD-3-Clause",
    #"CC0-1.0",
    "ISC",
    "MIT",
    #"OpenSSL",
    "Unicode-DFS-2016",
    #"Zlib",
]
private = { ignore = true }

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
